### PR TITLE
Gameboy Color Support (Very early)

### PR DESCRIPTION
**Pull request by brNX**
It's in the title

Color support added, new peripherals added etc...
Clock switching isn't done yet (Fast mode 4->8Mhz) and probably lots of little things that still need to be done.

View it as alpha, but some games are playable.

### CODE REVIEW

**Comment by sorgelig** [comment]
Is it ready for release.
I mean, even with alpha stage of GBC mode, will it work as before in GB mode?

**Comment by brNX** [comment]
Yes,  the GB mode works as before , and the GB games can also be played in GBC mode with color palettes like in the real GBC. You can choose the palette on bootup like on the real device

**Comment by sorgelig** [comment]
is there prerequisites to play GBC?
After i switch to GBC mode i see black screen and so far i didn't find any game starting in this mode.
For example R-Type DX.gbc works fine in GB mode, doesn't work in GBC.
Street Fighter Alpha starts in GB mode with nag screen asking for GBC, but doesn't start in GBC mode.

**Comment by brNX** [comment]
yes, sorry, check the readme, you have to put the gbc bios/bootrom in the gameboy folder and rename it to boot1.rom

**Comment by sorgelig** [comment]
Oh, i didn't notice the update in readme, sorry.

**Comment by brNX** [comment]
no problem, I could've integrated it but I think it's better this way to avoid possible problems in the future, nintendo is ruthless lately with roms. R-type DX is one of the games that seem to work well actually.

**Comment by sorgelig** [comment]
yeah, it's better to keep it loadable.

**Pull request merged**
