### PR TITLE
Dual HDMI/Analog output

### PR DESCRIPTION
**Pull request by rattboi**
* Parameterized LCD module to allow for padding
* Using two LCD modules, one for HDMI, one for analog out
* Needed new clock to generate 320x240@59.7Hz pixel clock
* Removed 4x vertical multiply stuff in lcd/top-level

### CODE REVIEW

**Comment by sorgelig** [comment]
While i'm ok with friendly VGA output for this core i don't like this particular changes:
1) having separate clock is great instability for the core. Analog video is not so strict to pixel clock, so consider some clock enable for existing clock to generate CE_PIXEL instead.
2) I don't see why core needs to use 2 LCD modules. If VGA output is good, then it can be used for HDMI as well. So, consider to simplify the design.
3) To comply with MiSTer standard it's not allowed to change input/output signals of emu module and any if higher level modules, so again about (2).

@brNX please check this PR in order to fit the general idea to the core if it doesn't break the logic.

**Comment by brNX** [comment]
will do

**Comment by rattboi** [comment]
First, thanks for taking the time to look over my PR. 

Without context, it can be hard to know why different decisions have been made. I can try and discuss each point you made and why I thought it was necessary.

1) While I agree adding a new output from the PLL is more drastic than just using a clock divider, I needed a pixel clock of ~6.03 to drive the 320x240@59.7Hz buffer, when you add the fp/bp/sync time as well. Since the base clock is 67MHz, I'd need to divide down by 11, which is awkward, and doesn't actually quite get us the value that we want.

2) The purpose of the two LCD modules is to generate two different kinds of output. Since the VGA output is padded from 160x144 -> 320x240, if I were to drive the HDMI with the same signals, it would also have the padding included, which is non-ideal for many reasons, such as not being able to be make full vertical use of the screen with the extra 48 pixel padding at the top and bottom.

3) I needed to expose both the VGA and HDMI signals to the emu module in order to pad *just* the VGA signals, as described in (2). However, I did also remove the unused DDR signals, and while I think it's a reasonable change, I didn't mean to ship that specific change along with this PR. I can revert that change if it's bothersome.

**Comment by sorgelig** [comment]
1) it's nothing awkward to have divider 11. It's way better than having other clock domain. Believe me having different clock domain will bring a lot of instability to the core. If not now then later. It's when you change some unrelated part of code like audio, but then you get a broken video. I've dealt with such problems in other cores and it's the best to avoid it as much as possible. 
Analog signal is not so strict to exact clock. So 67/11 = 6.09 is basically the same as 6.03

2 and 3) HDMI scaler use only part of video where VGA_DE is active. So with proper blanking to exact 160x144 HDMI scaler will use exactly 160x144 portion of video. This is how all cores work and you see a full screen on HDMI without borders regardless the original analog video resolution.

**Comment by rattboi** [comment]
Ok, great. I'll try to apply your recommendations and come back with a better update. 

I had no idea that VGA_DE was used in that way, so that's great to know.

**Comment by sorgelig** [comment]
Good! I close this PR. You are free to open a new PR later.
It's better if you will make a new for of this repository, so your old changes won't go to new PR.

**Pull request closed without merging**
