### PR TITLE
GB clock simplification and general cleanups

### PR DESCRIPTION
**Pull request by brNX**
Simplified the clock in the gb module so that it takes clk_sys and uses ce and ce_2x to generate the 2 clocks.
It sped up compilation (14:36 -> 9:52 on my PC) , lowered resources and should add stability to the core.

### CODE REVIEW

**Comment by Kitrinx** [comment]
this PR makes my Codes changes work stably with no added compile time. Nice job!

**Comment by sorgelig** [comment]
What is the status of video. Still tearing?

**Comment by brNX** [comment]
yes the previous PR should be reverted for now I think until we come up with a better solution,  soltan/ghogan42 came up with a workaround that can be used for now using the scaler, the only negative is that hdmi doesn't work with it when using the gb core.
```
[Gameboy]
video_mode=320,8,32,24,240,4,3,16,6048
vga_scaler=1
vsync_adjust=0
vscale_mode=1

**Comment by sorgelig** [comment]
those who needs VGA, usually don't need the HDMI :)

**Comment by sorgelig** [comment]
I would add vsync_adjust=1 or 2 as well

**Comment by brNX** [comment]
> those who needs VGA, usually don't need the HDMI :)

exactly, yes I agree with vsync_adjust=2 should probably be used too

**Comment by Kitrinx** [comment]
when you get the reversion/base settled, I will cherry pick my codes update over it and submit

**Comment by sorgelig** [comment]
i've already updated the cheats :)

**Comment by Kitrinx** [comment]
Oh, thank you. 

BTW sorg: https://gamehacking.org/mister/
Locutus is working on getting it integrated in updating.
Works like magic.

**Comment by sorgelig** [comment]
Nice!
I'm getting old for games, so prefer relaxed play with invulnerability :)

**Comment by brNX** [comment]
Nice job with the cheats, will finally beat some shmups 😅

**Comment by sorgelig** [comment]
If they could name the cheat zips as in TOSEC, then it would be even better.

**Comment by Kitrinx** [comment]
Smokemonster packs are all using no-intro names which is what they use at gamehacking, so it matches automatically.

**Comment by sorgelig** [comment]
I have an idea. Gamehacking has CRC32 for ROM. How about to add CRC32 to the end on the zip name? In this case I can add match by name (if it matches except the CRC32 part of name) and by CRC32.

**Comment by sorgelig** [comment]
probably need to add some name format:
whatevername-[CCCCCCCC].zip
where CCCCCCCC is the CRC32 (8 symbols in HEX). If MiSTer will find like [12345678] before zip extension then it will be considered as CRC32

**Comment by brNX** [comment]
I like the crc32 , we're already using those when fishing for roms to apply patches

**Comment by Kitrinx** [comment]
I will ask rimsky if he will do this

**Comment by sorgelig** [comment]
Can you check with rimsky on which platforms headers are included into CRC32 and on which aren't?

**Comment by sorgelig** [comment]
I've pushed preliminary version with CRC32 support.
Tested on SNES - works good! So, no need to care about the name anymore!
CRC32 is not so strong check. Hope there won't be CRC32 collide of different games.

**Comment by Kitrinx** [comment]
Genesis, SMS/GG, SNES, TG16/SGFX, and Gameboy/color all use their internal headers, I think, so those would be included in the CRC. NES and FDS are probably the only rom types with artificial headers: NES uses two formats, iNES and UNIF, but we don't consider UNIF style valid roms on MiSTer, so just the 16 byte iNES. FDS works with or without headers, and some roms don't have one, so that's trickier.

On CRC collisions, if there are any, you could disambiguate by attempting to check the first few letters of the name, I guess. No easy answer there. If there are any, I don't think it will be many, CRC32 is used by many emulators to figure out the game.

**Comment by Kitrinx** [comment]
CRC is pretty useful for a lot of things, maybe someday it would be worth passing it to cores to use as identification for special quirks in games. In NES for instance it could be used to assist with mapper variations in some problem games like Startropics that don't normally have the correct NES2.0 header.

**Comment by sorgelig** [comment]
CRC32 in FPGA is easy. No point to send it over.
In current implementation everything left from mask 0x3FF is considered as header and then skipped from CRC32 calculation. 
Also, find cheat by crc32 is fall-back after the whole name check. So, it's always possible to override by zip without CRC32 in the name, so it will be used first if matched by name.

**Pull request merged**
