### PR TITLE
Dual HDMI/Analog output (try #2)

### PR DESCRIPTION
**Pull request by rattboi**
* Parameterized LCD module to allow for padding
* Removed 4x vertical multiply stuff in lcd/top-level

### CODE REVIEW

**Comment by rattboi** [comment]
https://kanyid.org/linx/selif/e41vziaw.mp4 

Here's the thing in action. this is only an HDMI capture, unfortunately, as I don't have the right hardware yet to capture analog (it's coming).

A couple things to note:
* You can see at the beginning of the video that it's running at 60.4 Hz refresh.
* You can't see it in the video, but it appears the OSD is resized to fit into the VGA_DE-defined frame (160x144) on VGA, so it is quite small. I'll try and add a picture to demonstrate, if you'd like.

**Comment by sorgelig** [comment]
Yes, OSD is supposed to fit into DE area as outside area can be hidden.
It can be kept like this for now.

**Comment by Kitrinx** [comment]
With this PR, HDMI has some nasty tearing in all vsync_adjust modes, including vsync_adjust = 0

**Comment by brNX** [comment]
Sorry for being late, long day at work today.

I was just going to comment the same thing as @Kitrinx,  this should probably be reverted until a better solution is found.

I didn't dislike the idea of handling hdmi and vga separately because of the padding, I would probably use 2 line buffers instead of 2 lcd's to do it to save resources but if they are there why not use them, this can later be optimized.

**Comment by sorgelig** [comment]
i will check it probably tomorrow. If i won't find the quick fix i will revert it for future improvements.

**Comment by rattboi** [comment]
I think I have some ideas on improvements, but the VGA ones could take a bit to get right. I feel that in the interim, going with the emu module with both VGA and HDMI signals going out would allow the original clock for HDMI, and we would still have tearing for VGA for a bit as I get a good solution in place.

**Pull request merged**
